client:
 peers:
  peer1:
    host: "localhost"
    port: 7051
    event_host: "event_host1"
    event_port: 2

  peer2:
    host: "localhost"
    port: 7056
    event_host: "event_host2"
    event_port: 4

 tls:
  enabled: false
  certificate:
  serverhostoverride:

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 tcert:
  batch:
    size: 200

 orderer:
  host: "localhost"
  port: 7050

 logging:
  level: info

 msp:
  id: "DEFAULT"
  url: "http://localhost:8888"
  clientPath: "./integration_test/test_resources/"

 keystore:
  path: "C:/keystore"