peers:
  peer1:
    host: "localhost"
    port: 7051
    event_host: "event_host1"
    event_port: 2

  peer2:
    host: "localhost"
    port: 7056
    event_host: "event_host2"
    event_port: 4

tls:
  enabled: false
  certificate:
  serverhostoverride:

security:
  enabled: false
  hashAlgorithm: SHA2
  level: 256

tcert:
  batch:
    size: 200